### ISSUE TITLE
fileheader.other_config 不生效

### ISSUE THREAD

**Issue by XingXiaoWu** [caizhengxin/fileheader-template#1]
```
 "fileheader.other_config": {
    "email": "xxx",
    "describtion":"",
  },
```
生成的时候并没有这两项

**Comment by caizhengxin** [comment]
custom template

吴兴 <notifications@github.com> 于2020年2月17日周一 下午3:57写道：

**Comment by caizhengxin** [comment]
[image: custom_template.png.png]

蔡正心 <jankincai12@gmail.com> 于2020年3月5日周四 下午11:40写道：

**Comment by XingXiaoWu** [comment]
You seem to have shut it down without doing anything
My problem has not been solved
